title: Less is fun
description: Wentao's Homepage.
show_downloads: false
google_analytics: _includes/analytics.html
theme: jekyll-theme-architect
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one